### ISSUE TITLE
Firmware Version: 0x0 = (unknown) WARNING: Communication failure, is the MFRC522 properly connected?

### ISSUE THREAD

**Issue by javier237** [miguelbalboa/rfid#299]
### Step 2: Describe your environment

 * OS version: ___7__
 * Arduino IDE version: ___1.8.2__
 * MFRC522 Library version: __1.3.2___
 * Arduino device: _Mega____
 * MFRC522 device: ___RC522__
  
### Step 3: Describe the problem

Firmware Version: 0x0 = (unknown)
WARNING: Communication failure, is the MFRC522 properly connected?
![desktop 25-03-2017 21-39-21-222](https://cloud.githubusercontent.com/assets/26685789/24329663/1004be84-11c2-11e7-8fdf-ace58f68f9af.png)

I have double checked the connections and all are done according to the typical connections of MEGA.

I have tried and replaced arduino MEGA and the RFID RC-522 but I have got no success.

Would be great if you could help.
Thank you

**Comment by Rotzbua** [comment]
You didnt config the code:

```c++
#define RST_PIN         9          // Configurable, see typical pin layout above
#define SS_PIN 10 // Configurable, see typical pin layout above

**Comment by javier237** [comment]
like that 
![desktop 26-03-2017 11-39-35-727](https://cloud.githubusercontent.com/assets/26685789/24334098/14975acc-1219-11e7-8a76-964f9153dff1.png)

**Comment by Rotzbua** [comment]
You have to change the values of the pins to that value you have connected them.
E.g.:
```c++
#define RST_PIN       5          // Configurable, see typical pin layout above
#define SS_PIN 53 // Configurable, see typical pin layout above

**Comment by surabhi96** [comment]
@Rotzbua Hey, I am using the uno only but I still get the same error.
I have connected RST to digital pin 9 and SDA to pin 10

**Comment by Rotzbua** [comment]
@surabhi96 Please use the large [troubleshooting](https://github.com/miguelbalboa/rfid/blob/master/README.rst#troubleshooting). If nothing works contact your supplier for help or replacement.

**Comment by rafabrasail** [comment]
I'had the same problem. I've solved this problem welding the wires.

**Comment by TheMatth** [comment]
Hey ! I had the same problem as you all, and I fixed it by connecting the wires directly from the Arduino UNO to the RFID reader without a breadboard. 
Hope this tip can help some of you ;)

**Comment by Lollywash** [comment]
I was having the exact same problem,
I fixed by:
Verifying what board I have (Arduino Uno, Arduino Mega, Arduino Nano, Arduino Pro micro)
Then depending on that physically changing my pins for the correct board.
You can see all the different pins in an example file from the MFRC522 examples (I used the DumpInfo Example) 
![image](https://user-images.githubusercontent.com/39814137/40814704-d31b6f20-650f-11e8-9e2f-f1ad2441a98d.png)
Then in the code you must change 2 values:
"RST_PIN"
"SS_PIN"
Right here:
![image](https://user-images.githubusercontent.com/39814137/40814785-6fd1549c-6510-11e8-9329-7de8a29d4b9d.png)
Hope this helps thanks

**Comment by usermigallon** [comment]
Hello,
I change this for arduino mega:
// Create MFRC522 instance.
constexpr uint8_t RST_PIN = 5;     // Configurable, see typical pin layout above
constexpr uint8_t SS_PIN = 53;     // Configurable, see typical pin layout above
and works

**Comment by Lollywash** [comment]
Yes that would be the correct configuration fire the Arduino Mega as stated by the example program (highlighted in my previous post)

**Comment by usermigallon** [comment]
Right, thank you for your post.
Can I ask you? if i lost my tag how can deleted from code ?

**Comment by anistark** [comment]
Same issue still facing. I'm using RFID RC522 and followed the exact configurations. 

```
Firmware Version: 0x0 = (unknown)
WARNING: Communication failure, is the MFRC522 properly connected?
MFRC522 software version = 0
Scan PICC to see UID, SAK, type, and data blocks...
```

Anybody found any solution?

**Comment by Cevalik** [comment]
i have arduino uno and getting firmware error 0x0 (unknown)
connections are fine but don't know why it is showing communication failure

**Comment by marlonmilesmg** [comment]
i have arduino uno, 2 * mfrc522 rfid readers and getting firmware error 0x0 (unknown)
connections are fine but don't know why it is showing communication failure
![arduinoerror](https://user-images.githubusercontent.com/39700735/53767174-a2b55c80-3edd-11e9-8da7-e90d42837c44.PNG)

**Comment by marlonmilesmg** [comment]
i have arduino uno, 2 * mfrc522 rfid readers and getting firmware error 0x0 (unknown)
connections are fine but don't know why it is showing communication failure
![Uploading ArduinoError.PNG…]()

**Comment by marlonmilesmg** [comment]
Soldering is the way to go guys. Worked for me!!!

**Comment by DarkiStar** [comment]
see my PR
`https://github.com/miguelbalboa/rfid/pull/476`

**Comment by mimya01** [comment]
**same problem.**

**Comment by mimya01** [comment]
Soldering is the way  for me

**Comment by GianPieers** [comment]
¿Y para nodemcu-spe32s funciona?

**Comment by awebwemu** [comment]
> 
> ### Step 1: Are you in the right place?
> ### Step 2: Describe your environment
> 
>     * OS version: _**7**
> 
>     * Arduino IDE version: _**1.8.2**
> 
>     * MFRC522 Library version: **1.3.2**_
> 
>     * Arduino device: _Mega____
> 
>     * MFRC522 device: _**RC522**
> 
> 
> ### Step 3: Describe the problem
> 
> Firmware Version: 0x0 = (unknown)
> WARNING: Communication failure, is the MFRC522 properly connected?
> ![desktop 25-03-2017 21-39-21-222](https://cloud.githubusercontent.com/assets/26685789/24329663/1004be84-11c2-11e7-8fdf-ace58f68f9af.png)
> 
> I have double checked the connections and all are done according to the typical connections of MEGA.
> 
> I have tried and replaced arduino MEGA and the RFID RC-522 but I have got no success.
> 
> Would be great if you could help.
> Thank you

Can use arduino uno?

**Comment by tonyMath97** [comment]
Estou com o mesmo problema no Arduino  Uno, as configurações das portas estão corretas, não posso soldar, alguém alguma outra alternativa?

**Comment by batmacumba** [comment]
Infelizmente tem que soldar mesmo, tony. Boa sorte!

**Comment by tonyMath97** [comment]
> Infelizmente tem que soldar mesmo, tony. Boa sorte!

Como se tratava apenas de um projeto da faculdade (e não possuo solda), apenas forcei o contato do modulo RFID com a Barra de pinos que estava conectada na protoboard e funcionou perfeitamente. Mas a solução é soldar mesmo.

**Comment by pyyan11ss** [comment]
tinggal solder aja si tony goblok

**Comment by Rizky-anugerah** [comment]
> tinggal solder aja si tony goblok

weeeeyyyy, sans bray

**Comment by AYODEJI006** [comment]
I also faced the same problem.
The firmware version error does not matter.
what i did to solve the problem is:
I use separate voltage 3.3V to power RFID reader instead of connecting it to arduino 3.3V pin
but remember to connect arduino GND to the separate 3.3V GND.
![WhatsApp Image 2023-05-06 at 19 31 28](https://user-images.githubusercontent.com/80019656/236641143-2c88d0ee-d4f2-4260-84c2-f7dfdd558940.jpg)

**Comment by yuvrajtayal1202** [comment]
dwwcw

**Comment by kyle-yeh** [comment]
It may be that the voltage is too low due to poor contact. I pressed it to make the board more in contact with it.

**Comment by empflow** [comment]
> It may be that the voltage is too low due to poor contact. I pressed it to make the board more in contact with it.

This was exactly my issue! Thanks! I just had to tape it a bit better

**Comment by cyberajk** [comment]
Check to make sure SS pin is not being used by another device or shield.  My shield was using SS pin 10, and when I switched the RFID board to a free pin and updated the code, it fixed the connection error.

**Comment by baoOyster** [comment]
Even I've keep it hardly, nothing happen :://

**Comment by kazuwsx** [comment]
@marlonmilesmg 

> Soldering is the way to go guys. Worked for me!!!

I saved this comment.
Really appreciate your comment.

Guys, soldering is the trueth.

**Comment by Yar00myr** [comment]
If you could tell me what the problem is, I would be very thankful:

Arduino IDE version: _2.3.6
MFRC522 Library version: 1.14.12
Device: Freenove v4 (v4.1)
MFRC522 device: RFID-RC522


Code:
`#include <SPI.h>
#include <MFRC522.h>

#define RST_PIN 4
#define SS_PIN 5

MFRC522 mfrc522(SS_PIN, RST_PIN);

void setup() {
  Serial.begin(9600);
  SPI.begin();
  mfrc522.PCD_Init();
  Serial.println(F("Тестування RC522..."));
  mfrc522.PCD_DumpVersionToSerial();
}

void loop() {
  if (!mfrc522.PICC_IsNewCardPresent()) return;
  if (!mfrc522.PICC_ReadCardSerial()) return;
  
  Serial.print(F("UID:"));
  for (byte i = 0; i < mfrc522.uid.size; i++) {
    Serial.print(mfrc522.uid.uidByte[i] < 0x10 ? " 0" : " ");
    Serial.print(mfrc522.uid.uidByte[i], HEX);
  }
  Serial.println();
  mfrc522.PICC_HaltA();
}`


Photo: 

![Image](https://github.com/user-attachments/assets/c52b93a2-3fce-4e5b-b5b4-b6eed70d50a5)
